{
 "title": "Inter-Pod Network Analysis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Traffic between Client and Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n) by (destination_namespace)",
     "legendFormat": "Received by Server"
    }
   ]
  },
  {
   "title": "Traffic Received by Server across AZs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n    * on (destination_podname) group_left(destination_node)\n    label_replace(\n        label_replace(kube_pod_info{namespace=\"target-app\", created_by_name=~\"target-(.*)\"}, \"destination_podname\", \"$1\", \"pod\", \"(.*)\"), \"destination_node\", \"$1\", \"node\", \"(.*)\"\n    )\n    * on (destination_node) group_left(destination_zone)\n    label_replace(\n        label_replace(sum by (node, label_topology_kubernetes_io_zone) (kube_node_labels), \"destination_node\", \"$1\", \"node\", \"(.*)\"), \"destination_zone\", \"$1\", \"label_topology_kubernetes_io_zone\", \"(.*)\"\n    )\n) by (destination_zone)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AZ Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    ceil(\n        (\n            sum(\n                rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n                * on (source_podname) group_left(source_node)\n                label_replace(\n                    label_replace(kube_pod_info{namespace=\"source-app\", created_by_name=~\"source-(.*)\"}, \"source_podname\", \"$1\", \"pod\", \"(.*)\"), \"source_node\", \"$1\", \"node\", \"(.*)\"\n                )\n                * on (source_node) group_left(zone)\n                label_replace(\n                    label_replace(sum by (node, label_topology_kubernetes_io_zone) (kube_node_labels), \"source_node\", \"$1\", \"node\", \"(.*)\"), \"zone\", \"$1\", \"label_topology_kubernetes_io_zone\", \"(.*)\"\n                )\n            ) by (destination_podname, source_podname, zone)\n        )\n        + on (destination_podname, source_podname, zone) group_left()\n        (\n            sum(\n                rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n                * on (destination_podname) group_left(destination_node)\n                label_replace(\n                    label_replace(kube_pod_info{namespace=\"target-app\", created_by_name=~\"target-(.*)\"}, \"destination_podname\", \"$1\", \"pod\", \"(.*)\"), \"destination_node\", \"$1\", \"node\", \"(.*)\"\n                )\n                * on (destination_node) group_left(zone)\n                label_replace(\n                    label_replace(sum by (node, label_topology_kubernetes_io_zone) (kube_node_labels), \"destination_node\", \"$1\", \"node\", \"(.*)\"), \"zone\", \"$1\", \"label_topology_kubernetes_io_zone\", \"(.*)\"\n                )\n            ) by (destination_podname, source_podname, zone)\n        )\n    ) / 2 # we are divinding because we are summing values in '+on()' function to find the Same AZ traffic\n) OR on() vector(0)",
     "legendFormat": "Same AZ Traffic"
    },
    {
     "expr": "sum(\n    rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n)\n-\nsum(\n    ceil(\n        (\n            sum(\n                rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n                * on (source_podname) group_left(source_node)\n                label_replace(\n                    label_replace(kube_pod_info{namespace=\"source-app\", created_by_name=~\"source-(.*)\"}, \"source_podname\", \"$1\", \"pod\", \"(.*)\"), \"source_node\", \"$1\", \"node\", \"(.*)\"\n                )\n                * on (source_node) group_left(zone)\n                label_replace(\n                    label_replace(sum by (node, label_topology_kubernetes_io_zone) (kube_node_labels), \"source_node\", \"$1\", \"node\", \"(.*)\"), \"zone\", \"$1\", \"label_topology_kubernetes_io_zone\", \"(.*)\"\n                )\n            ) by (destination_podname, source_podname, zone)\n        )\n        + on (destination_podname, source_podname, zone) group_left()\n        (\n            sum(\n                rate(networkobservability_adv_forward_bytes{source_namespace=\"source-app\", source_workload_name=~\"source-(.*)\", destination_namespace=\"target-app\", destination_workload_name=~\"target-(.*)\"}[$__rate_interval])\n                * on (destination_podname) group_left(destination_node)\n                label_replace(\n                    label_replace(kube_pod_info{namespace=\"target-app\", created_by_name=~\"target-(.*)\"}, \"destination_podname\", \"$1\", \"pod\", \"(.*)\"), \"destination_node\", \"$1\", \"node\", \"(.*)\"\n                )\n                * on (destination_node) group_left(zone)\n                label_replace(\n                    label_replace(sum by (node, label_topology_kubernetes_io_zone) (kube_node_labels), \"destination_node\", \"$1\", \"node\", \"(.*)\"), \"zone\", \"$1\", \"label_topology_kubernetes_io_zone\", \"(.*)\"\n                )\n            ) by (destination_podname, source_podname, zone)\n        )\n    ) / 2\n)",
     "legendFormat": "Cross AZ Traffic"
    }
   ]
  }
 ]
}